import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { authorizedFetch } from './auth'
import './plc-source-overlay.css'

type PlcSource = {
  area: string
  source: 'real' | 'simulator'
  source_label: string
  model: string
  protocol: string
  host: string
  port: number
  rack: number
  slot: number
  read_only: boolean
}

type PlcSourceResponse = {
  sources: Record<string, PlcSource>
}

const AREAS = ['EAF', 'LF', 'CCM'] as const

export function PlcSourceOverlay() {
  const [sources, setSources] = useState<Record<string, PlcSource>>({})
  const [targets, setTargets] = useState<HTMLElement[]>([])

  useEffect(() => {
    let cancelled = false
    let timer: number | null = null

    const refresh = async () => {
      try {
        const response = await authorizedFetch('/api/v1/plc-sources')
        if (!response.ok) return
        const payload = await response.json() as PlcSourceResponse
        if (!cancelled) setSources(payload.sources ?? {})
      } finally {
        if (!cancelled) timer = window.setTimeout(() => { void refresh() }, 5000)
      }
    }

    void refresh()
    return () => {
      cancelled = true
      if (timer !== null) window.clearTimeout(timer)
    }
  }, [])

  useEffect(() => {
    const root = document.getElementById('root')
    if (!root) return

    const syncTargets = () => {
      setTargets(Array.from(document.querySelectorAll<HTMLElement>('.production-station')))
    }

    syncTargets()
    const observer = new MutationObserver(syncTargets)
    observer.observe(root, { childList: true, subtree: true })
    return () => observer.disconnect()
  }, [])

  return (
    <>
      {AREAS.map((area, index) => {
        const target = targets[index]
        const source = sources[area]
        if (!target || !source) return null

        return createPortal(
          <div
            className={`plc-source-anchor ${source.source}`}
            tabIndex={0}
            aria-label={`${area} source ${source.source_label}`}
          >
            <span className="plc-source-dot" />
            <strong>{source.source_label}</strong>
            <div className="plc-source-popup" role="tooltip">
              <header>
                <small>{area} LEVEL 1 SOURCE</small>
                <strong>{source.source_label}</strong>
              </header>
              <dl>
                <div><dt>Model</dt><dd>{source.model}</dd></div>
                <div><dt>Protocol</dt><dd>{source.protocol}</dd></div>
                <div><dt>Host</dt><dd>{source.host}:{source.port}</dd></div>
                <div><dt>Rack / Slot</dt><dd>{source.rack} / {source.slot}</dd></div>
                <div><dt>Gateway mode</dt><dd>{source.read_only ? 'READ ONLY' : 'READ / WRITE'}</dd></div>
              </dl>
              <p>
                {source.source === 'real'
                  ? 'Live process values are being read from the configured Siemens PLC.'
                  : 'Process values are being generated by the S7-400 style simulator.'}
              </p>
            </div>
          </div>,
          target,
          `plc-source-${area}`,
        )
      })}
    </>
  )
}
